### ISSUE TITLE
"Cannot load accept" despite bash 5.2.0(1)-alpha

### ISSUE THREAD

**Issue by ForwardFeed** [dzove855/Bash-web-server#7]
#### I tried to make it work on the 5.2.0(1)-alpha version of bash
- i have the "cannot load accept" error
#### I tried with bash 5.0
- Applying the patch said it has some rejection, it is normal?
- Compiling the patched accept.c isn't smooth at all i have no clue how to do it.
- Also even if i had it to compile what i am supposed to do with the binary in the end?

Any idea? thanks.

**Comment by dzove855** [comment]
To get the the script qork with 5.2 you will need to change the shebang to point to 5.2 and accept should be ine BASH_LOADABLE_PATH (i will need to change the behaviour of this and use the default bash global var)


Acceot has been published with bash 5.1, so the minimum requirement would be bash 5.1

**Comment by ForwardFeed** [comment]
Nice i found it in /usr/local/lib/bash/
Now it works, thanks.
