### ISSUE TITLE
Accept requests in lan

### ISSUE THREAD

**Issue by iaGuoZhi** [dzove855/Bash-web-server#9]
Currently the web server can only be accessed in the same machine, I want to support accessing from lan without netcat and other tools. Any ideas about it?

**Comment by dzove855** [comment]
The Webservee can be used putside the lan, you just need to specify the bind address with the variable:

export BIND_ADDRESS=0.0.0.0 and then start the script

**Comment by iaGuoZhi** [comment]
Exactly, Thanks!
